#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}


# branches to build
branches:
  only:
    - master


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: 
  - Visual Studio 2019

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# clone directory
clone_folder: C:\projects\Inline-Engine



# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to add several platforms to build matrix:
platform:
  - x64

# to add several configurations to build matrix:
configuration:
  - Debug
  - RelWithDebInfo

build:
  parallel: true
  project: C:\projects\Inline-Engine\build\Inline-Engine.sln
  verbosity: minimal


# scripts to run before build
before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G "Visual Studio 16 2019" -DCMAKE_SYSTEM_VERSION=10.0

#---------------------------------#
#             testing             #
#---------------------------------#

# run tests
test_script:
  - ps : |-
      mkdir test_results
      cd test_results
      iex "C:\projects\Inline-Engine\build\Bin\$env:CONFIGURATION\Test_Unit.exe --reporter junit --out test.xml"
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test.xml))

